// <auto-generated />
using System;
using MeuCrudCompleto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeuCrudCompleto.Migrations
{
    [DbContext(typeof(MeuCrudCompletoContext))]
    [Migration("20220303004830_OutrasEntidades")]
    partial class OutrasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MeuCrudCompleto.Models.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("MeuCrudCompleto.Models.RegistroDeVendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Montante")
                        .HasColumnType("double");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("RegistroDeVendas");
                });

            modelBuilder.Entity("MeuCrudCompleto.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BaseSalario")
                        .HasColumnType("double");

                    b.Property<DateTime>("DataAniversario")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Departamentoid")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Departamentoid");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("MeuCrudCompleto.Models.RegistroDeVendas", b =>
                {
                    b.HasOne("MeuCrudCompleto.Models.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("MeuCrudCompleto.Models.Vendedor", b =>
                {
                    b.HasOne("MeuCrudCompleto.Models.Departamento", "Departamento")
                        .WithMany("Vendedores")
                        .HasForeignKey("Departamentoid");
                });
#pragma warning restore 612, 618
        }
    }
}
